services:
  - type: web
    name: agro-monitor-backend
    runtime: docker
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromConfig: true
      - key: CLIMA_API_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true

