services:
  - type: web
    name: agro-monitor-backend
    runtime: docker # <--- Aquí le decimos que use nuestro Dockerfile
    plan: free
    region: ohio
    envVars:
      - key: DATABASE_URL
        fromConfig: true # La tomaremos de la UI de Render o Neon
      - key: CLIMA_API_KEY
        sync: false # La pondremos manualmente en Render por seguridad
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true # Render generará una segura por nosotros

