# Generated by Django 6.0.2 on 2026-02-28 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Huerto Norte o Invernadero', max_length=100)),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('presion', models.FloatField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('icono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='clima.location')),
            ],
            options={
                'verbose_name_plural': 'Weather Histories',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
